services:
  piston-api:
    image: ghcr.io/engineer-man/piston:latest
    container_name: compile99-piston
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - piston_data:/piston
    restart: unless-stopped

volumes:
  piston_data:
